#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerGarageOS2019414
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="fabiofin_ireland")]
	public partial class DataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertVehicle(Vehicle instance);
    partial void UpdateVehicle(Vehicle instance);
    partial void DeleteVehicle(Vehicle instance);
    partial void InsertCustomer_Vehicle(Customer_Vehicle instance);
    partial void UpdateCustomer_Vehicle(Customer_Vehicle instance);
    partial void DeleteCustomer_Vehicle(Customer_Vehicle instance);
    partial void InsertService_Type(Service_Type instance);
    partial void UpdateService_Type(Service_Type instance);
    partial void DeleteService_Type(Service_Type instance);
    partial void InsertStaff(Staff instance);
    partial void UpdateStaff(Staff instance);
    partial void DeleteStaff(Staff instance);
    partial void InsertItems_Part(Items_Part instance);
    partial void UpdateItems_Part(Items_Part instance);
    partial void DeleteItems_Part(Items_Part instance);
    partial void InsertBorder(Border instance);
    partial void UpdateBorder(Border instance);
    partial void DeleteBorder(Border instance);
    partial void InsertService_Status(Service_Status instance);
    partial void UpdateService_Status(Service_Status instance);
    partial void DeleteService_Status(Service_Status instance);
    partial void InsertHtry_Stts_Bking(Htry_Stts_Bking instance);
    partial void UpdateHtry_Stts_Bking(Htry_Stts_Bking instance);
    partial void DeleteHtry_Stts_Bking(Htry_Stts_Bking instance);
    partial void InsertBooking(Booking instance);
    partial void UpdateBooking(Booking instance);
    partial void DeleteBooking(Booking instance);
    partial void InsertInvoice(Invoice instance);
    partial void UpdateInvoice(Invoice instance);
    partial void DeleteInvoice(Invoice instance);
    #endregion
		
		public DataContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["fabiofin_irelandConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<Vehicle> Vehicles
		{
			get
			{
				return this.GetTable<Vehicle>();
			}
		}
		
		public System.Data.Linq.Table<Customer_Vehicle> Customer_Vehicles
		{
			get
			{
				return this.GetTable<Customer_Vehicle>();
			}
		}
		
		public System.Data.Linq.Table<Service_Type> Service_Types
		{
			get
			{
				return this.GetTable<Service_Type>();
			}
		}
		
		public System.Data.Linq.Table<Staff> Staffs
		{
			get
			{
				return this.GetTable<Staff>();
			}
		}
		
		public System.Data.Linq.Table<Items_Part> Items_Parts
		{
			get
			{
				return this.GetTable<Items_Part>();
			}
		}
		
		public System.Data.Linq.Table<Border> Borders
		{
			get
			{
				return this.GetTable<Border>();
			}
		}
		
		public System.Data.Linq.Table<Service_Status> Service_Status
		{
			get
			{
				return this.GetTable<Service_Status>();
			}
		}
		
		public System.Data.Linq.Table<Htry_Stts_Bking> Htry_Stts_Bkings
		{
			get
			{
				return this.GetTable<Htry_Stts_Bking>();
			}
		}
		
		public System.Data.Linq.Table<Booking> Bookings
		{
			get
			{
				return this.GetTable<Booking>();
			}
		}
		
		public System.Data.Linq.Table<VW_Booking> VW_Bookings
		{
			get
			{
				return this.GetTable<VW_Booking>();
			}
		}
		
		public System.Data.Linq.Table<VW_Order> VW_Orders
		{
			get
			{
				return this.GetTable<VW_Order>();
			}
		}
		
		public System.Data.Linq.Table<VW_Invoice> VW_Invoices
		{
			get
			{
				return this.GetTable<VW_Invoice>();
			}
		}
		
		public System.Data.Linq.Table<Invoice> Invoices
		{
			get
			{
				return this.GetTable<Invoice>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="fabiofin_ireland.PR_TimeAvailable")]
		public ISingleResult<PR_TimeAvailableResult> PR_TimeAvailable([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string dataSelected)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dataSelected);
			return ((ISingleResult<PR_TimeAvailableResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_d.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_customer;
		
		private string _name;
		
		private string _email;
		
		private string _password;
		
		private string _phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_customerChanging(int value);
    partial void Onid_customerChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NChar(45) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NChar(45) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.Vehicle")]
	public partial class Vehicle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_vehicle;
		
		private string _model;
		
		private string _brand;
		
		private string _engine;
		
		private string _type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_vehicleChanging(int value);
    partial void Onid_vehicleChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void OnengineChanging(string value);
    partial void OnengineChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public Vehicle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vehicle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_vehicle
		{
			get
			{
				return this._id_vehicle;
			}
			set
			{
				if ((this._id_vehicle != value))
				{
					this.Onid_vehicleChanging(value);
					this.SendPropertyChanging();
					this._id_vehicle = value;
					this.SendPropertyChanged("id_vehicle");
					this.Onid_vehicleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(50)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="VarChar(50)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engine", DbType="VarChar(10)")]
		public string engine
		{
			get
			{
				return this._engine;
			}
			set
			{
				if ((this._engine != value))
				{
					this.OnengineChanging(value);
					this.SendPropertyChanging();
					this._engine = value;
					this.SendPropertyChanged("engine");
					this.OnengineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.Customer_Vehicle")]
	public partial class Customer_Vehicle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_custVehicle;
		
		private System.Nullable<int> _id_vehicle;
		
		private System.Nullable<int> _id_customer;
		
		private string _license;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_custVehicleChanging(int value);
    partial void Onid_custVehicleChanged();
    partial void Onid_vehicleChanging(System.Nullable<int> value);
    partial void Onid_vehicleChanged();
    partial void Onid_customerChanging(System.Nullable<int> value);
    partial void Onid_customerChanged();
    partial void OnlicenseChanging(string value);
    partial void OnlicenseChanged();
    #endregion
		
		public Customer_Vehicle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_custVehicle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_custVehicle
		{
			get
			{
				return this._id_custVehicle;
			}
			set
			{
				if ((this._id_custVehicle != value))
				{
					this.Onid_custVehicleChanging(value);
					this.SendPropertyChanging();
					this._id_custVehicle = value;
					this.SendPropertyChanged("id_custVehicle");
					this.Onid_custVehicleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vehicle", DbType="Int")]
		public System.Nullable<int> id_vehicle
		{
			get
			{
				return this._id_vehicle;
			}
			set
			{
				if ((this._id_vehicle != value))
				{
					this.Onid_vehicleChanging(value);
					this.SendPropertyChanging();
					this._id_vehicle = value;
					this.SendPropertyChanged("id_vehicle");
					this.Onid_vehicleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int")]
		public System.Nullable<int> id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_license", DbType="VarChar(15)")]
		public string license
		{
			get
			{
				return this._license;
			}
			set
			{
				if ((this._license != value))
				{
					this.OnlicenseChanging(value);
					this.SendPropertyChanging();
					this._license = value;
					this.SendPropertyChanged("license");
					this.OnlicenseChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.Service_Types")]
	public partial class Service_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_service;
		
		private string _service_type1;
		
		private System.Nullable<int> _service_price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_serviceChanging(int value);
    partial void Onid_serviceChanged();
    partial void Onservice_type1Changing(string value);
    partial void Onservice_type1Changed();
    partial void Onservice_priceChanging(System.Nullable<int> value);
    partial void Onservice_priceChanged();
    #endregion
		
		public Service_Type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_service", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_service
		{
			get
			{
				return this._id_service;
			}
			set
			{
				if ((this._id_service != value))
				{
					this.Onid_serviceChanging(value);
					this.SendPropertyChanging();
					this._id_service = value;
					this.SendPropertyChanged("id_service");
					this.Onid_serviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="service_type", Storage="_service_type1", DbType="VarChar(20)")]
		public string service_type1
		{
			get
			{
				return this._service_type1;
			}
			set
			{
				if ((this._service_type1 != value))
				{
					this.Onservice_type1Changing(value);
					this.SendPropertyChanging();
					this._service_type1 = value;
					this.SendPropertyChanged("service_type1");
					this.Onservice_type1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_price", DbType="Int")]
		public System.Nullable<int> service_price
		{
			get
			{
				return this._service_price;
			}
			set
			{
				if ((this._service_price != value))
				{
					this.Onservice_priceChanging(value);
					this.SendPropertyChanging();
					this._service_price = value;
					this.SendPropertyChanged("service_price");
					this.Onservice_priceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.Staff")]
	public partial class Staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_staff;
		
		private string _staff_name;
		
		private System.Nullable<System.DateTime> _birth_dt;
		
		private string _staff_phone;
		
		private string _email;
		
		private string _password;
		
		private string _staff_type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_staffChanging(int value);
    partial void Onid_staffChanged();
    partial void Onstaff_nameChanging(string value);
    partial void Onstaff_nameChanged();
    partial void Onbirth_dtChanging(System.Nullable<System.DateTime> value);
    partial void Onbirth_dtChanged();
    partial void Onstaff_phoneChanging(string value);
    partial void Onstaff_phoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onstaff_typeChanging(string value);
    partial void Onstaff_typeChanged();
    #endregion
		
		public Staff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_staff", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_staff
		{
			get
			{
				return this._id_staff;
			}
			set
			{
				if ((this._id_staff != value))
				{
					this.Onid_staffChanging(value);
					this.SendPropertyChanging();
					this._id_staff = value;
					this.SendPropertyChanged("id_staff");
					this.Onid_staffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_name", DbType="VarChar(50)")]
		public string staff_name
		{
			get
			{
				return this._staff_name;
			}
			set
			{
				if ((this._staff_name != value))
				{
					this.Onstaff_nameChanging(value);
					this.SendPropertyChanging();
					this._staff_name = value;
					this.SendPropertyChanged("staff_name");
					this.Onstaff_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birth_dt", DbType="Date")]
		public System.Nullable<System.DateTime> birth_dt
		{
			get
			{
				return this._birth_dt;
			}
			set
			{
				if ((this._birth_dt != value))
				{
					this.Onbirth_dtChanging(value);
					this.SendPropertyChanging();
					this._birth_dt = value;
					this.SendPropertyChanged("birth_dt");
					this.Onbirth_dtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_phone", DbType="VarChar(50)")]
		public string staff_phone
		{
			get
			{
				return this._staff_phone;
			}
			set
			{
				if ((this._staff_phone != value))
				{
					this.Onstaff_phoneChanging(value);
					this.SendPropertyChanging();
					this._staff_phone = value;
					this.SendPropertyChanged("staff_phone");
					this.Onstaff_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(20)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_type", DbType="VarChar(30)")]
		public string staff_type
		{
			get
			{
				return this._staff_type;
			}
			set
			{
				if ((this._staff_type != value))
				{
					this.Onstaff_typeChanging(value);
					this.SendPropertyChanging();
					this._staff_type = value;
					this.SendPropertyChanged("staff_type");
					this.Onstaff_typeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.Items_Parts")]
	public partial class Items_Part : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_items_parts;
		
		private System.Data.Linq.Binary _item_name;
		
		private System.Nullable<int> _price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_items_partsChanging(int value);
    partial void Onid_items_partsChanged();
    partial void Onitem_nameChanging(System.Data.Linq.Binary value);
    partial void Onitem_nameChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    #endregion
		
		public Items_Part()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_items_parts", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_items_parts
		{
			get
			{
				return this._id_items_parts;
			}
			set
			{
				if ((this._id_items_parts != value))
				{
					this.Onid_items_partsChanging(value);
					this.SendPropertyChanging();
					this._id_items_parts = value;
					this.SendPropertyChanged("id_items_parts");
					this.Onid_items_partsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_name", DbType="VarBinary(100)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary item_name
		{
			get
			{
				return this._item_name;
			}
			set
			{
				if ((this._item_name != value))
				{
					this.Onitem_nameChanging(value);
					this.SendPropertyChanging();
					this._item_name = value;
					this.SendPropertyChanged("item_name");
					this.Onitem_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.[Order]")]
	public partial class Border : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_order;
		
		private System.Nullable<int> _id_booking;
		
		private System.Nullable<int> _id_customer;
		
		private System.Nullable<int> _id_staff;
		
		private System.Nullable<int> _id_service;
		
		private System.Nullable<int> _id_parts_items;
		
		private int _id_status;
		
		private string _order_notes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_orderChanging(int value);
    partial void Onid_orderChanged();
    partial void Onid_bookingChanging(System.Nullable<int> value);
    partial void Onid_bookingChanged();
    partial void Onid_customerChanging(System.Nullable<int> value);
    partial void Onid_customerChanged();
    partial void Onid_staffChanging(System.Nullable<int> value);
    partial void Onid_staffChanged();
    partial void Onid_serviceChanging(System.Nullable<int> value);
    partial void Onid_serviceChanged();
    partial void Onid_parts_itemsChanging(System.Nullable<int> value);
    partial void Onid_parts_itemsChanged();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void Onorder_notesChanging(string value);
    partial void Onorder_notesChanged();
    #endregion
		
		public Border()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_order", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_order
		{
			get
			{
				return this._id_order;
			}
			set
			{
				if ((this._id_order != value))
				{
					this.Onid_orderChanging(value);
					this.SendPropertyChanging();
					this._id_order = value;
					this.SendPropertyChanged("id_order");
					this.Onid_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_booking", DbType="Int")]
		public System.Nullable<int> id_booking
		{
			get
			{
				return this._id_booking;
			}
			set
			{
				if ((this._id_booking != value))
				{
					this.Onid_bookingChanging(value);
					this.SendPropertyChanging();
					this._id_booking = value;
					this.SendPropertyChanged("id_booking");
					this.Onid_bookingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int")]
		public System.Nullable<int> id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_staff", DbType="Int")]
		public System.Nullable<int> id_staff
		{
			get
			{
				return this._id_staff;
			}
			set
			{
				if ((this._id_staff != value))
				{
					this.Onid_staffChanging(value);
					this.SendPropertyChanging();
					this._id_staff = value;
					this.SendPropertyChanged("id_staff");
					this.Onid_staffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_service", DbType="Int")]
		public System.Nullable<int> id_service
		{
			get
			{
				return this._id_service;
			}
			set
			{
				if ((this._id_service != value))
				{
					this.Onid_serviceChanging(value);
					this.SendPropertyChanging();
					this._id_service = value;
					this.SendPropertyChanged("id_service");
					this.Onid_serviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_parts_items", DbType="Int")]
		public System.Nullable<int> id_parts_items
		{
			get
			{
				return this._id_parts_items;
			}
			set
			{
				if ((this._id_parts_items != value))
				{
					this.Onid_parts_itemsChanging(value);
					this.SendPropertyChanging();
					this._id_parts_items = value;
					this.SendPropertyChanged("id_parts_items");
					this.Onid_parts_itemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int NOT NULL")]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_notes", DbType="VarChar(200)")]
		public string order_notes
		{
			get
			{
				return this._order_notes;
			}
			set
			{
				if ((this._order_notes != value))
				{
					this.Onorder_notesChanging(value);
					this.SendPropertyChanging();
					this._order_notes = value;
					this.SendPropertyChanged("order_notes");
					this.Onorder_notesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.Service_Status")]
	public partial class Service_Status : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_status;
		
		private string _status_type;
		
		private string _status_description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_statusChanging(int value);
    partial void Onid_statusChanged();
    partial void Onstatus_typeChanging(string value);
    partial void Onstatus_typeChanged();
    partial void Onstatus_descriptionChanging(string value);
    partial void Onstatus_descriptionChanged();
    #endregion
		
		public Service_Status()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_type", DbType="VarChar(50)")]
		public string status_type
		{
			get
			{
				return this._status_type;
			}
			set
			{
				if ((this._status_type != value))
				{
					this.Onstatus_typeChanging(value);
					this.SendPropertyChanging();
					this._status_type = value;
					this.SendPropertyChanged("status_type");
					this.Onstatus_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_description", DbType="VarChar(150)")]
		public string status_description
		{
			get
			{
				return this._status_description;
			}
			set
			{
				if ((this._status_description != value))
				{
					this.Onstatus_descriptionChanging(value);
					this.SendPropertyChanging();
					this._status_description = value;
					this.SendPropertyChanged("status_description");
					this.Onstatus_descriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.Htry_Stts_Bking")]
	public partial class Htry_Stts_Bking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_histBooking;
		
		private System.Nullable<int> _id_booking;
		
		private System.Nullable<int> _id_status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_histBookingChanging(int value);
    partial void Onid_histBookingChanged();
    partial void Onid_bookingChanging(System.Nullable<int> value);
    partial void Onid_bookingChanged();
    partial void Onid_statusChanging(System.Nullable<int> value);
    partial void Onid_statusChanged();
    #endregion
		
		public Htry_Stts_Bking()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_histBooking", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_histBooking
		{
			get
			{
				return this._id_histBooking;
			}
			set
			{
				if ((this._id_histBooking != value))
				{
					this.Onid_histBookingChanging(value);
					this.SendPropertyChanging();
					this._id_histBooking = value;
					this.SendPropertyChanged("id_histBooking");
					this.Onid_histBookingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_booking", DbType="Int")]
		public System.Nullable<int> id_booking
		{
			get
			{
				return this._id_booking;
			}
			set
			{
				if ((this._id_booking != value))
				{
					this.Onid_bookingChanging(value);
					this.SendPropertyChanging();
					this._id_booking = value;
					this.SendPropertyChanged("id_booking");
					this.Onid_bookingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int")]
		public System.Nullable<int> id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.Booking")]
	public partial class Booking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_booking;
		
		private System.Nullable<System.DateTime> _reservationDate;
		
		private string _customer_notes;
		
		private System.Nullable<int> _id_customer;
		
		private System.Nullable<int> _id_vehicle;
		
		private System.Nullable<int> _id_service;
		
		private System.Nullable<int> _id_time;
		
		private string _licence;
		
		private System.Nullable<int> _id_status;
		
		private System.Nullable<int> _id_staff;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_bookingChanging(int value);
    partial void Onid_bookingChanged();
    partial void OnreservationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnreservationDateChanged();
    partial void Oncustomer_notesChanging(string value);
    partial void Oncustomer_notesChanged();
    partial void Onid_customerChanging(System.Nullable<int> value);
    partial void Onid_customerChanged();
    partial void Onid_vehicleChanging(System.Nullable<int> value);
    partial void Onid_vehicleChanged();
    partial void Onid_serviceChanging(System.Nullable<int> value);
    partial void Onid_serviceChanged();
    partial void Onid_timeChanging(System.Nullable<int> value);
    partial void Onid_timeChanged();
    partial void OnlicenceChanging(string value);
    partial void OnlicenceChanged();
    partial void Onid_statusChanging(System.Nullable<int> value);
    partial void Onid_statusChanged();
    partial void Onid_staffChanging(System.Nullable<int> value);
    partial void Onid_staffChanged();
    #endregion
		
		public Booking()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_booking", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_booking
		{
			get
			{
				return this._id_booking;
			}
			set
			{
				if ((this._id_booking != value))
				{
					this.Onid_bookingChanging(value);
					this.SendPropertyChanging();
					this._id_booking = value;
					this.SendPropertyChanged("id_booking");
					this.Onid_bookingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservationDate", DbType="Date")]
		public System.Nullable<System.DateTime> reservationDate
		{
			get
			{
				return this._reservationDate;
			}
			set
			{
				if ((this._reservationDate != value))
				{
					this.OnreservationDateChanging(value);
					this.SendPropertyChanging();
					this._reservationDate = value;
					this.SendPropertyChanged("reservationDate");
					this.OnreservationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_notes", DbType="VarChar(500)")]
		public string customer_notes
		{
			get
			{
				return this._customer_notes;
			}
			set
			{
				if ((this._customer_notes != value))
				{
					this.Oncustomer_notesChanging(value);
					this.SendPropertyChanging();
					this._customer_notes = value;
					this.SendPropertyChanged("customer_notes");
					this.Oncustomer_notesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int")]
		public System.Nullable<int> id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vehicle", DbType="Int")]
		public System.Nullable<int> id_vehicle
		{
			get
			{
				return this._id_vehicle;
			}
			set
			{
				if ((this._id_vehicle != value))
				{
					this.Onid_vehicleChanging(value);
					this.SendPropertyChanging();
					this._id_vehicle = value;
					this.SendPropertyChanged("id_vehicle");
					this.Onid_vehicleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_service", DbType="Int")]
		public System.Nullable<int> id_service
		{
			get
			{
				return this._id_service;
			}
			set
			{
				if ((this._id_service != value))
				{
					this.Onid_serviceChanging(value);
					this.SendPropertyChanging();
					this._id_service = value;
					this.SendPropertyChanged("id_service");
					this.Onid_serviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_time", DbType="Int")]
		public System.Nullable<int> id_time
		{
			get
			{
				return this._id_time;
			}
			set
			{
				if ((this._id_time != value))
				{
					this.Onid_timeChanging(value);
					this.SendPropertyChanging();
					this._id_time = value;
					this.SendPropertyChanged("id_time");
					this.Onid_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_licence", DbType="NChar(15)")]
		public string licence
		{
			get
			{
				return this._licence;
			}
			set
			{
				if ((this._licence != value))
				{
					this.OnlicenceChanging(value);
					this.SendPropertyChanging();
					this._licence = value;
					this.SendPropertyChanged("licence");
					this.OnlicenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int")]
		public System.Nullable<int> id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this.Onid_statusChanging(value);
					this.SendPropertyChanging();
					this._id_status = value;
					this.SendPropertyChanged("id_status");
					this.Onid_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_staff", DbType="Int")]
		public System.Nullable<int> id_staff
		{
			get
			{
				return this._id_staff;
			}
			set
			{
				if ((this._id_staff != value))
				{
					this.Onid_staffChanging(value);
					this.SendPropertyChanging();
					this._id_staff = value;
					this.SendPropertyChanged("id_staff");
					this.Onid_staffChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.VW_Booking")]
	public partial class VW_Booking
	{
		
		private int _id_booking;
		
		private System.Nullable<System.DateTime> _reservationDate;
		
		private string _customer_notes;
		
		private System.Nullable<int> _id_customer;
		
		private string _name;
		
		private string _type;
		
		private System.Nullable<int> _id_vehicle;
		
		private string _model;
		
		private string _brand;
		
		private string _engine;
		
		private System.Nullable<int> _id_service;
		
		private string _service_type;
		
		private System.Nullable<int> _id_time;
		
		private System.Nullable<int> _time;
		
		private System.Nullable<int> _id_status;
		
		private string _status_type;
		
		private System.Nullable<int> _id_staff;
		
		private string _staff_name;
		
		public VW_Booking()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_booking", DbType="Int NOT NULL")]
		public int id_booking
		{
			get
			{
				return this._id_booking;
			}
			set
			{
				if ((this._id_booking != value))
				{
					this._id_booking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservationDate", DbType="Date")]
		public System.Nullable<System.DateTime> reservationDate
		{
			get
			{
				return this._reservationDate;
			}
			set
			{
				if ((this._reservationDate != value))
				{
					this._reservationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_notes", DbType="VarChar(500)")]
		public string customer_notes
		{
			get
			{
				return this._customer_notes;
			}
			set
			{
				if ((this._customer_notes != value))
				{
					this._customer_notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int")]
		public System.Nullable<int> id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this._id_customer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_vehicle", DbType="Int")]
		public System.Nullable<int> id_vehicle
		{
			get
			{
				return this._id_vehicle;
			}
			set
			{
				if ((this._id_vehicle != value))
				{
					this._id_vehicle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(50)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this._model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="VarChar(50)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this._brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engine", DbType="VarChar(10)")]
		public string engine
		{
			get
			{
				return this._engine;
			}
			set
			{
				if ((this._engine != value))
				{
					this._engine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_service", DbType="Int")]
		public System.Nullable<int> id_service
		{
			get
			{
				return this._id_service;
			}
			set
			{
				if ((this._id_service != value))
				{
					this._id_service = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_type", DbType="VarChar(20)")]
		public string service_type
		{
			get
			{
				return this._service_type;
			}
			set
			{
				if ((this._service_type != value))
				{
					this._service_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_time", DbType="Int")]
		public System.Nullable<int> id_time
		{
			get
			{
				return this._id_time;
			}
			set
			{
				if ((this._id_time != value))
				{
					this._id_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Int")]
		public System.Nullable<int> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int")]
		public System.Nullable<int> id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this._id_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_type", DbType="VarChar(50)")]
		public string status_type
		{
			get
			{
				return this._status_type;
			}
			set
			{
				if ((this._status_type != value))
				{
					this._status_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_staff", DbType="Int")]
		public System.Nullable<int> id_staff
		{
			get
			{
				return this._id_staff;
			}
			set
			{
				if ((this._id_staff != value))
				{
					this._id_staff = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_name", DbType="VarChar(50)")]
		public string staff_name
		{
			get
			{
				return this._staff_name;
			}
			set
			{
				if ((this._staff_name != value))
				{
					this._staff_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.VW_Order")]
	public partial class VW_Order
	{
		
		private int _id_order;
		
		private System.Nullable<int> _id_booking;
		
		private System.Nullable<System.DateTime> _reservationDate;
		
		private string _customer_notes;
		
		private System.Nullable<int> _id_customer;
		
		private string _name;
		
		private System.Nullable<int> _id_staff;
		
		private string _staff_name;
		
		private System.Nullable<int> _id_service;
		
		private string _service_type;
		
		private System.Nullable<int> _service_price;
		
		private System.Nullable<int> _id_status;
		
		private string _status_type;
		
		public VW_Order()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_order", DbType="Int NOT NULL")]
		public int id_order
		{
			get
			{
				return this._id_order;
			}
			set
			{
				if ((this._id_order != value))
				{
					this._id_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_booking", DbType="Int")]
		public System.Nullable<int> id_booking
		{
			get
			{
				return this._id_booking;
			}
			set
			{
				if ((this._id_booking != value))
				{
					this._id_booking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservationDate", DbType="Date")]
		public System.Nullable<System.DateTime> reservationDate
		{
			get
			{
				return this._reservationDate;
			}
			set
			{
				if ((this._reservationDate != value))
				{
					this._reservationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_notes", DbType="VarChar(500)")]
		public string customer_notes
		{
			get
			{
				return this._customer_notes;
			}
			set
			{
				if ((this._customer_notes != value))
				{
					this._customer_notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int")]
		public System.Nullable<int> id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this._id_customer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_staff", DbType="Int")]
		public System.Nullable<int> id_staff
		{
			get
			{
				return this._id_staff;
			}
			set
			{
				if ((this._id_staff != value))
				{
					this._id_staff = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_staff_name", DbType="VarChar(50)")]
		public string staff_name
		{
			get
			{
				return this._staff_name;
			}
			set
			{
				if ((this._staff_name != value))
				{
					this._staff_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_service", DbType="Int")]
		public System.Nullable<int> id_service
		{
			get
			{
				return this._id_service;
			}
			set
			{
				if ((this._id_service != value))
				{
					this._id_service = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_type", DbType="VarChar(20)")]
		public string service_type
		{
			get
			{
				return this._service_type;
			}
			set
			{
				if ((this._service_type != value))
				{
					this._service_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_price", DbType="Int")]
		public System.Nullable<int> service_price
		{
			get
			{
				return this._service_price;
			}
			set
			{
				if ((this._service_price != value))
				{
					this._service_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_status", DbType="Int")]
		public System.Nullable<int> id_status
		{
			get
			{
				return this._id_status;
			}
			set
			{
				if ((this._id_status != value))
				{
					this._id_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_type", DbType="VarChar(50)")]
		public string status_type
		{
			get
			{
				return this._status_type;
			}
			set
			{
				if ((this._status_type != value))
				{
					this._status_type = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.VW_Invoice")]
	public partial class VW_Invoice
	{
		
		private int _id_invoice;
		
		private System.Nullable<int> _id_order;
		
		private System.Nullable<int> _id_booking;
		
		private System.Nullable<int> _id_customer;
		
		private string _name;
		
		private System.Nullable<int> _id_service;
		
		private string _service_type;
		
		private System.Nullable<int> _service_price;
		
		private System.Nullable<int> _id_items_parts;
		
		private string _item_name;
		
		private System.Nullable<int> _price;
		
		public VW_Invoice()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_invoice", DbType="Int NOT NULL")]
		public int id_invoice
		{
			get
			{
				return this._id_invoice;
			}
			set
			{
				if ((this._id_invoice != value))
				{
					this._id_invoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_order", DbType="Int")]
		public System.Nullable<int> id_order
		{
			get
			{
				return this._id_order;
			}
			set
			{
				if ((this._id_order != value))
				{
					this._id_order = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_booking", DbType="Int")]
		public System.Nullable<int> id_booking
		{
			get
			{
				return this._id_booking;
			}
			set
			{
				if ((this._id_booking != value))
				{
					this._id_booking = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int")]
		public System.Nullable<int> id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this._id_customer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_service", DbType="Int")]
		public System.Nullable<int> id_service
		{
			get
			{
				return this._id_service;
			}
			set
			{
				if ((this._id_service != value))
				{
					this._id_service = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_type", DbType="VarChar(20)")]
		public string service_type
		{
			get
			{
				return this._service_type;
			}
			set
			{
				if ((this._service_type != value))
				{
					this._service_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_price", DbType="Int")]
		public System.Nullable<int> service_price
		{
			get
			{
				return this._service_price;
			}
			set
			{
				if ((this._service_price != value))
				{
					this._service_price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_items_parts", DbType="Int")]
		public System.Nullable<int> id_items_parts
		{
			get
			{
				return this._id_items_parts;
			}
			set
			{
				if ((this._id_items_parts != value))
				{
					this._id_items_parts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_name", DbType="VarChar(50)")]
		public string item_name
		{
			get
			{
				return this._item_name;
			}
			set
			{
				if ((this._item_name != value))
				{
					this._item_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this._price = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="fabiofin_ireland.Invoice")]
	public partial class Invoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_invoice;
		
		private System.Nullable<int> _id_order;
		
		private System.Nullable<int> _id_booking;
		
		private System.Nullable<int> _id_customer;
		
		private System.Nullable<int> _id_service;
		
		private System.Nullable<int> _id_items_parts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_invoiceChanging(int value);
    partial void Onid_invoiceChanged();
    partial void Onid_orderChanging(System.Nullable<int> value);
    partial void Onid_orderChanged();
    partial void Onid_bookingChanging(System.Nullable<int> value);
    partial void Onid_bookingChanged();
    partial void Onid_customerChanging(System.Nullable<int> value);
    partial void Onid_customerChanged();
    partial void Onid_serviceChanging(System.Nullable<int> value);
    partial void Onid_serviceChanged();
    partial void Onid_items_partsChanging(System.Nullable<int> value);
    partial void Onid_items_partsChanged();
    #endregion
		
		public Invoice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_invoice", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_invoice
		{
			get
			{
				return this._id_invoice;
			}
			set
			{
				if ((this._id_invoice != value))
				{
					this.Onid_invoiceChanging(value);
					this.SendPropertyChanging();
					this._id_invoice = value;
					this.SendPropertyChanged("id_invoice");
					this.Onid_invoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_order", DbType="Int")]
		public System.Nullable<int> id_order
		{
			get
			{
				return this._id_order;
			}
			set
			{
				if ((this._id_order != value))
				{
					this.Onid_orderChanging(value);
					this.SendPropertyChanging();
					this._id_order = value;
					this.SendPropertyChanged("id_order");
					this.Onid_orderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_booking", DbType="Int")]
		public System.Nullable<int> id_booking
		{
			get
			{
				return this._id_booking;
			}
			set
			{
				if ((this._id_booking != value))
				{
					this.Onid_bookingChanging(value);
					this.SendPropertyChanging();
					this._id_booking = value;
					this.SendPropertyChanged("id_booking");
					this.Onid_bookingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_customer", DbType="Int")]
		public System.Nullable<int> id_customer
		{
			get
			{
				return this._id_customer;
			}
			set
			{
				if ((this._id_customer != value))
				{
					this.Onid_customerChanging(value);
					this.SendPropertyChanging();
					this._id_customer = value;
					this.SendPropertyChanged("id_customer");
					this.Onid_customerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_service", DbType="Int")]
		public System.Nullable<int> id_service
		{
			get
			{
				return this._id_service;
			}
			set
			{
				if ((this._id_service != value))
				{
					this.Onid_serviceChanging(value);
					this.SendPropertyChanging();
					this._id_service = value;
					this.SendPropertyChanged("id_service");
					this.Onid_serviceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_items_parts", DbType="Int")]
		public System.Nullable<int> id_items_parts
		{
			get
			{
				return this._id_items_parts;
			}
			set
			{
				if ((this._id_items_parts != value))
				{
					this.Onid_items_partsChanging(value);
					this.SendPropertyChanging();
					this._id_items_parts = value;
					this.SendPropertyChanged("id_items_parts");
					this.Onid_items_partsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class PR_TimeAvailableResult
	{
		
		private int _id_time;
		
		private System.Nullable<int> _time;
		
		private System.Nullable<System.DateTime> _reservationDate;
		
		private int _qtde_IdTime;
		
		private string _Status;
		
		public PR_TimeAvailableResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_time", DbType="Int NOT NULL")]
		public int id_time
		{
			get
			{
				return this._id_time;
			}
			set
			{
				if ((this._id_time != value))
				{
					this._id_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Int")]
		public System.Nullable<int> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reservationDate", DbType="Date")]
		public System.Nullable<System.DateTime> reservationDate
		{
			get
			{
				return this._reservationDate;
			}
			set
			{
				if ((this._reservationDate != value))
				{
					this._reservationDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtde_IdTime", DbType="Int NOT NULL")]
		public int qtde_IdTime
		{
			get
			{
				return this._qtde_IdTime;
			}
			set
			{
				if ((this._qtde_IdTime != value))
				{
					this._qtde_IdTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
